/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package houghtransform;

import java.awt.FileDialog;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Maksim
 */
public class HoughTransform extends javax.swing.JFrame {
    /**
     * Creates new form mainwindow
     */
    public HoughTransform() {
        initComponents();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) { 
                int promptResult = JOptionPane.showConfirmDialog(null, 
                        "Are you sure you want to exit?", "Exit...", 
                        JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(promptResult == JOptionPane.YES_OPTION) {
                    dispose();
                } else {
                    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
                }
            } 
        });
    }

    public void close(){
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTextField_FileName = new javax.swing.JTextField();
        jButton_Transform = new javax.swing.JButton();
        jButton_OpenFile = new javax.swing.JButton();
        jButton_Capture = new javax.swing.JButton();
        jButton_Exit = new javax.swing.JButton();
        jRadioButton_OpenCV = new javax.swing.JRadioButton();
        jRadioButton_MyTransform = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTextField_FileName.setText("house.jpg");

        jButton_Transform.setText("Transform");
        jButton_Transform.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_TransformMousePressed(evt);
            }
        });

        jButton_OpenFile.setText("Open File");
        jButton_OpenFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_OpenFileMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField_FileName, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Transform)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_OpenFile)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField_FileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton_Transform)
                .addComponent(jButton_OpenFile))
        );

        jButton_Capture.setText("Capture");
        jButton_Capture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_CaptureMousePressed(evt);
            }
        });

        jButton_Exit.setText("Exit");
        jButton_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton_ExitMousePressed(evt);
            }
        });

        buttonGroup1.add(jRadioButton_OpenCV);
        jRadioButton_OpenCV.setSelected(true);
        jRadioButton_OpenCV.setText("OpenCV");

        buttonGroup1.add(jRadioButton_MyTransform);
        jRadioButton_MyTransform.setText("MyTransform");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Exit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton_MyTransform)
                            .addComponent(jRadioButton_OpenCV)
                            .addComponent(jButton_Capture))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Capture)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton_OpenCV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton_MyTransform)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(jButton_Exit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_TransformMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_TransformMousePressed
        String fileName = jTextField_FileName.getText();
        int choiceT;
        try {
            if(jRadioButton_OpenCV.isSelected())
                choiceT = 1;
            else if (jRadioButton_MyTransform.isSelected())
                choiceT = 2;
            else 
                throw new IOException("Must be selected!!!");
            
            final Picture x = new Picture(fileName, choiceT);
        } catch (IOException ex) {
            System.out.println("File not exist!!!" + ex);
        }
    }//GEN-LAST:event_jButton_TransformMousePressed

    private void jButton_ExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ExitMousePressed
        close();
    }//GEN-LAST:event_jButton_ExitMousePressed

    private void jButton_OpenFileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_OpenFileMousePressed
        FileDialog file = new FileDialog(this);
        file.setFile("*.png;*.xpm;*.jpg");
        file.setFilenameFilter(null);
        file.setVisible(true);
        String directoryName = file.getDirectory();
        String fileName = file.getFile();
        if (!directoryName.isEmpty() && !fileName.isEmpty())
            jTextField_FileName.setText(directoryName + fileName);
    }//GEN-LAST:event_jButton_OpenFileMousePressed

    private void jButton_CaptureMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_CaptureMousePressed
        int choiceT;
        try {
            if(jRadioButton_OpenCV.isSelected())
                choiceT = 1;
            else if (jRadioButton_MyTransform.isSelected())
                choiceT = 2;
            else 
                throw new IOException("Must be selected!!!");
            
            CaptureJFrame x = new CaptureJFrame(choiceT);
            x.setVisible(true);
        } catch (IOException ex) {
            System.out.println("No access to camera!!!" + ex);
        }
    }//GEN-LAST:event_jButton_CaptureMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoughTransform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoughTransform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoughTransform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoughTransform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HoughTransform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_Capture;
    private javax.swing.JButton jButton_Exit;
    private javax.swing.JButton jButton_OpenFile;
    private javax.swing.JButton jButton_Transform;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton_MyTransform;
    private javax.swing.JRadioButton jRadioButton_OpenCV;
    private javax.swing.JTextField jTextField_FileName;
    // End of variables declaration//GEN-END:variables
}
